version: "3"
services:
  db:
    # イメージの指定
    image: mysql:8
    # データの永続化（ホスト側のtmp/dbディレクトリにマウントする）
    volumes:
      # mysqlのデータを永続化するために、ホスト側のディレクトリをマウントする
      - ./.db/mysql_data:/var/lib/mysql
    # 環境変数の指定（初期設定値）
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
  web:
    # Dockerfile のあるディレクトリのパスを指定（imageかbuildを必ず指定する必要がある）
    build: .
    # デフォルトのコマンド指定（Rails特有の問題解消とRails立ち上げを指定している）
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # データの永続化（ホスト側のカレントディレクトリにマウントする）
    volumes:
      - .:/app
    tty: true
    # ポートの指定（外部からのアクセス時のポート：Dockerコンテナからアクセス時のポート）
    ports:
      - "3000:3000"
    # 依存関係の指定（dbが起動した後に、webが起動するようになる）
    depends_on:
      - db
